export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_FILTERED_PRODUCTS = 'GET_FILTERED_PRODUCTS';
export const GET_CART = 'GET_CART';
export const GET_DRAWER_STATUS = 'GET_DRAWER_STATUS';
export const GET_DRAWER_TYPE = 'GET_DRAWER_TYPE';
export const GET_NUMBER = 'GET_NUMBER';
export const GET_TOTAL_ITEMS = 'GET_TOTAL_ITEMS';
